### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#226]
`top` shows that Pursuit is using ~95% of the CPU on the Linode box, pretty much constantly. I'm not sure if something changed which would cause this, or if it's an issue in some dependency.

**Comment by hdgarrood** [comment]
:( oops. I'm not sure either.

**Comment by jplatte** [comment]
If I `source config/development.env`, `stack exec pursuit` locally it idles at 0% CPU (clicking around a bit in the web browser only slightly increases the mem usage but otherwise does nothing). I only have a database of 4 packages though. Can I somehow download the `data/verified` or all of `data` from pursuit.purescript.org?

**Comment by hdgarrood** [comment]
@jplatte yes, it's all here: https://github.com/purescript/pursuit-backups

**Comment by hdgarrood** [comment]
I have a suspicion that this might be due to the forked Hoogle database regeneration thread getting stuck somehow; this would also explain #221.

**Comment by paf31** [comment]
@hdgarrood Do you think you'll have any time soon to have a look at this with me?

**Comment by hdgarrood** [comment]
Yep. Do you want to set a specific time?

I think I'd start off by aborting a Hoogle database regeneration if it takes more than, say, 30 seconds, and seeing if that makes any difference. I can't think of anything else that would cause this, except for perhaps a bug in Yesod or Warp or something.

**Comment by paf31** [comment]
Does tomorrow work for you? I'll be online tomorrow working on various things, if you have time.

**Comment by hdgarrood** [comment]
Ok, sure, I'll just join IRC whenever I'm available.

**Comment by paf31** [comment]
I looked into this a little. The Hoogle work directory is very full, and after deleting the temp files, I saw some error files with content like this:

```
Parse error 5:2: Unknown attribute: version
Parse error 51:2: Unknown attribute: version
Parse error 158:2: Unknown attribute: version
Parse error 210:9: Parse error: Data.Array.range
Parse error 249:10: Parse error: Data.Array.cons
Parse error 315:10: Parse error: Data.Array.index
Parse error 534:9: Parse error: Data.Array.difference
Parse error 695:2: Unknown attribute: version
Parse error 700:16: Parse error: !
Parse error 742:2: Unknown attribute: version
Parse error 760:10: Parse error: Control.Category.id
Parse error 772:10: Parse error: Control.Biapply.biapply
Parse error 781:10: Parse error: Control.Biapply.biapplyFirst
Parse error 790:10: Parse error: Control.Biapply.biapplySecond
Parse error 961:2: Unknown attribute: version
Parse error 968:16: Parse error: !
Parse error 1563:2: Unknown attribute: version
Parse error 1679:2: Unknown attribute: version
Parse error 1717:2: Unknown attribute: version
Parse error 1723:17: Parse error: !
Parse error 1777:2: Unknown attribute: version
Parse error 1848:2: Unknown attribute: version
Parse error 2010:10: Parse error: Data.Functor.Contravariant.cmap
Parse error 2019:10: Parse error: Data.Functor.Contravariant.cmap
```

**Comment by hdgarrood** [comment]
Right, we should fix that, although I don't see how that could cause the problems we're seeing. Which temporary files did you delete? Did it make a difference?

**Comment by hdgarrood** [comment]
Oh also, what do the logs say about hoogle database regenerations?

**Comment by paf31** [comment]
Where should I look? I don't see any information in the default log file.

**Comment by hdgarrood** [comment]
I'm just looking to see when DB regenerations are being triggered and how long each is taking. There's only one log file, as far as I'm aware. If that information isn't available in it then we should add some more logging so that it is, I think.

**Comment by paf31** [comment]
Solved temporarily by removing the Hoogle database regeneration, but I'll leave this open, since it's not really solved yet.
